import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { Providers } from '@/lib/provider';
import { Toaster } from '@/components/ui/sonner';
import NextTopLoader from 'nextjs-toploader';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  weight: '500',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Widebay Drones',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={montserrat.className}
    >
      <body className={`${montserrat.variable} antialiased`}>
        <NextTopLoader
          color='#0055d4'
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing='ease'
          speed={200}
          shadow='0 0 10px #0055d4,0 0 5px #0055d4'
        />
        <Providers>{children}</Providers>
        <Toaster richColors />
      </body>
    </html>
  );
}
