import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/provider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Widebay Drones",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={montserrat.className}
    >
      <body className={`${montserrat.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
